### ISSUE TITLE
Crash playing some songs

### ISSUE THREAD

**Issue by AB-Law** [NextFire/apple-music-discord-rpc#1]
Crashed while playing a song and got this error

Traceback (most recent call last):
  File "music-rpc-full.py", line 59, in <module>
    end = time.time() + float(infos[4]) - float(infos[5]))
ValueError: could not convert string to float: 'Wiz Khalifa & Juicy J) - Single'

**Comment by NextFire** [comment]
Hi! Can you play the same song and send me the output of `osascript -e "tell application \"Music\"" -e "get {name, artist, album, year, duration} of current track & {player position}" -e "end tell"` in Terminal? Thanks.

**Comment by AB-Law** [comment]
So here's the output I get:

`apple-music-discord-rpc % osascript -e "tell application \"Music\"" -e "get {name, artist, album, year, duration} of current track & {player position}" -e "end tell"
86:103: execution error: Music got an error: Can’t get name of current track. (-1728)`

Here's the song where the script fails:
https://music.apple.com/in/album/23-feat-miley-cyrus-wiz-khalifa-juicy-j/1444899578?i=1444899827

**Comment by NextFire** [comment]
Ok thanks, I currently don't have an Apple Music subscription to test myself (my whole music library is local). Is it not working only with this track or is this a general issue for all Apple Music streamed songs?
Can you also give me the output of `osascript -e "tell application \"Music\"" -e "get properties of current track" -e "end tell"`? (while still playing the same track)

**Comment by AB-Law** [comment]
Hey,
So the script works with most of the songs, however there are errors for a few songs, one of which is this song.
Anyways, here's the output:
`% osascript -e "tell application \"Music\"" -e "get properties of current track" -e "end tell"
29:39: execution error: Music got an error: Can’t get properties of current track. (-1728)
`

**Comment by NextFire** [comment]
Well, after a quick search it appears that this issue is probably linked to the Music app itself and the way it miss to report sometimes informations through its AppleScript interface (related issue maybe: https://github.com/Jean-Tinland/simple-bar/issues/58#issuecomment-735455006). So I guess there is nothing we can do except waiting/telling Apple to fix it as my only way to communicate with the Music app and to get playing informations is through the AppleScript commands I asked you to test before.

However what I can do for the time being is to make the script not crashing when this issue occurs...

**Comment by NextFire** [comment]
Thanks for all the informations provided! Commit 1d2c94277fe570043f6336da91c181403ae3d00c fixes the crashes by still displaying player state in Discord without the tracks informations when they cannot be retrieved. Please update to the latest version!
