### ISSUE TITLE
add animated artwork (suggestion)

### ISSUE THREAD

**Issue by Alonso245** [NextFire/apple-music-discord-rpc#69]
Since most album covers are animated now, is there a way to put them in the rpc?

**Comment by sorae42** [comment]
Someone did be able to fetch them: https://github.com/bunnykek/Apple-Music-Animated-Artwork-Fetcher 

Though I don't really see the point of this since no one really look at a profile for a long time. And fetching one will take a while and by that time it starts playing the cover, people already clicked off the profile.

**Comment by NextFire** [comment]
Thank you for linking this project.
Also I should mention that afaik Discord rich presence protocol doesn't allow us to use a video for the thumbnail.
